Test19
cyberriver/rails_rack pull request #1
Opened 2022-08-26 23:05 UTC by cyberriver

done rack app

2022-08-27 17:16 UTC, BubuntuClu requested changes

2022-08-27 17:16 UTC, BubuntuClu commented on format.rb
> +  CORRECT_FORMAT = ['year', 'month', 'day', 'hour', 'minute', 'second']
почему это отдельный массив, а не `DATE_DIRECTIVES.keys`?

2022-08-27 17:16 UTC, BubuntuClu commented on format.rb
> +module Format
не вижу особого смысла в этом файле. ты же его просто заинклудил в основной класс. больше в другие файлы этот файл не инклудиться, да и врядли будет, так как логика слишком специфичная чтобы быть потребной в нескольких классах

2022-08-27 17:16 UTC, BubuntuClu commented on app.rb
> +  def set_params(request)
пустой метод

2022-08-27 17:16 UTC, BubuntuClu commented on app/router.rb
> +      begin
логика построенная на исключениях изначально какая-то неправильная. зачем тебе тут `send`?

2022-08-27 17:16 UTC, BubuntuClu commented on app/router.rb
> +    [200, { "Content-Type" => "text/plain" }, [msg]]
для ответа используй `Rack::Response`

2022-08-27 17:16 UTC, BubuntuClu commented on app/router.rb
> +  def not_found(msg = "Not Found")
для не найдено может быть другой текст?

2022-08-27 17:16 UTC, BubuntuClu commented on app.rb
> +  def incorrect_parameters(args)
почему ответ может слать и этот класс и роутер? кажется, как будто ты размешал ответственность классов на несколько, а не одному дал эту обязанность

2022-08-27 21:30 UTC, cyberriver commented on app.rb
> +  def set_params(request)
поправил

2022-08-27 21:31 UTC, cyberriver commented on app/router.rb
> +  def not_found(msg = "Not Found")
убрал

2022-08-27 21:32 UTC, cyberriver commented on app/router.rb
> +    [200, { "Content-Type" => "text/plain" }, [msg]]
готово

2022-08-27 21:42 UTC, cyberriver commented on app.rb
> +  def incorrect_parameters(args)
да, идея была в том, что этот класс отфильтровывает траффик и только потом передает на роутер, если в траффике не хватает параметров или введены некорректные параметры, то он его просто блочит, а если введены то пускает дальше. Такой прокси балансировщик

2022-08-27 21:45 UTC, cyberriver commented on app/router.rb
> +      begin
идея в том, что есть отдельно роутер, который обрабатывает запросы и отдельно приложение, которое ему туда их направляет. запросы в роутер могут любые приходить, соответственно он как бы эмулирует, что выдаются ресурсы. например /time это ресурс, и вместо того, чтобы проверять path, я просто решил его превратить в метод, так получает все что не запускается, соответственно не находится, а все что запускается значит правильно.

логика такая была. это дает возможность сделать универсальный роутер

2022-08-28 17:20 UTC, BubuntuClu requested changes

2022-08-28 17:20 UTC, BubuntuClu commented on app.rb
> +  def response (body, status, headers)
почему у тебя ответ отправляется в не скольких файлах? тут и в `router`. кто-то один должен это делать.

2022-08-28 17:20 UTC, BubuntuClu commented on format.rb
> +module Format
все так же это подемешивание методов в класс. а зачем это? сделай класс-сервис, который будет парсить строку и говорить успешно ли распарсил. если успешно то отдает время по формату, если не успешно, тогда сообщение с ошибками в формате

`initialize/call/success?/time_string/invalid_string`
примерно такой набор методов.

тогда логика по парсингу будет полностью в нем происходить. а логика по обработке запроса/отдаче ответа будет на внешнем классе.
и получается все 2 файла

2022-08-28 17:20 UTC, BubuntuClu commented on app.rb
>  class App
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2022-08-28 17:23 UTC, BubuntuClu requested changes

2022-08-28 17:23 UTC, BubuntuClu commented on app.rb
> +      incorrect_parameters(@diff) #filtering request by incorrect parameters
воу воу, тут `@diff` вообще инстанс переменная из другого модуля. не стоит так делать, это крайне не очевидно. сделай через сервис и поулчай из него неправильные форматы. текущая реализация вариант плохой. и еще потому что тут массив, тебе надо костылять 13ю строку

2022-08-28 17:23 UTC, BubuntuClu commented on app/router.rb
> +      response = Rack::Response.new(
а зачем тут переменная?

2022-08-28 19:41 UTC, cyberriver commented on format.rb
> +module Format
готово

2022-08-28 20:26 UTC, cyberriver commented on app.rb
> +  def response (body, status, headers)
убрал router, оставил только тут. теперь 1 файл

2022-08-28 20:27 UTC, cyberriver commented on app.rb
>  class App
разбил приложение 2 части

2022-08-28 20:27 UTC, cyberriver commented on app/router.rb
> +      response = Rack::Response.new(
роутера больше нет))

2022-08-28 21:19 UTC, BubuntuClu requested changes

2022-08-28 21:19 UTC, BubuntuClu commented on time_formatter.rb
> +class TimeFormatter
пример вызова и реализации класса
```
 date_object = TimeFormatter.new
    date_object.call(request.params['format'].split(","))
    if date_object.success?
      response(200, date_object.response_time)
    else
      response(404, 'Unknown time format' + ' ' + date_object.invalid_string.join(', '))
    end
```

```
class TimeFormatter

  FORMAT_TIME = {"year" => "Y", "month" => "m", "day" => "d", "hour" => "H", "minute" => "M", "second" => "S"}.freeze

  attr_reader :invalid_string

  def initialize
    @valid_string = []
    @invalid_string = []
  end

  def call(request_with_data)
    acceptable_format = FORMAT_TIME.keys
    request_with_data.each do |element_date|
      if acceptable_format.include? element_date
        @valid_string << FORMAT_TIME[element_date]
      else
        @invalid_string << element_date
      end
    end
  end

  def success?
    @invalid_string.empty?
  end

  def response_time
    Time.now.strftime("%" + @valid_string.join('-%'))
  end
end
```

2022-08-28 21:19 UTC, BubuntuClu commented on time_formatter.rb
> +class TimeFormatter
компактно все, у тебя куча методов

2022-08-29 05:26 UTC, cyberriver commented on time_formatter.rb
> +class TimeFormatter
понял)

2022-08-29 05:27 UTC, merged